update_catalog:
  description: >
    Update the product catalog with the latest information.
  expected_output: >
    An updated product catalog with accurate and up-to-date information.
  agent: catalog_manager

check_prices:
  description: >
    Check and update product prices dynamically.
  expected_output: >
    A list of updated product prices with the best deals.
  agent: price_checker

check_inventory:
  description: >
    Track inventory levels and notify when stock is low.
  expected_output: >
    A report of inventory levels and restocking notifications.
  agent: inventory_manager

suggest_products:
  description: >
    Suggest products to users based on their preferences and cart contents.
  expected_output: >
    A list of recommended products for the user.
  agent: recommendation_engine

manage_cart:
  description: >
    Manage the shopping cart, add/remove items, and calculate totals.
  expected_output: >
    A dictionary containing the updated cart contents and total price.
  agent: cart_manager